# Main navigation

main:
  - name: Ideas
    url: /ideas/
    weight: 10

  - name: Speaking
    url: /speaking/
    weight: 20

  - name: Media
    url: /media/
    weight: 30

  - name: Writing
    url: /writing/
    weight: 40

  - name: Research
    url: /research/
    weight: 50

  - name: About
    url: /about/
    weight: 60

  - name: Connect
    url: /connect/
    weight: 70
